### ISSUE TITLE
Differential ADC support

### ISSUE THREAD

**Issue by Harvie** [arduino/ArduinoCore-avr#102]
**ATMega2560, ATMega32u4** and ATTiny85 have **differential ADCs with variable gain** and mux on chip. Can you please add support for these or arduino HAL abstraction? so everybody can use this with same ease as we use digitalRead() and analogRead()?

This probably covers **Arduino Mega 2560, Arduino Leonardo** and possibly Arduino Pro Micro (not sure about pinout). Also it might be usefull to support ATTiny85, since i use arduino to program these, but i understand there's no official Arduino board carrying ATTiny85.

Here are some resources:

https://forum.arduino.cc/index.php?topic=239030.0
https://www.davidpilling.com/wiki/index.php/DiffADC
Also datasheets of mentioned uCs have all related registers explained.

Thanks

**Comment by lxrobotics** [comment]
Hi @Harvie :wave: Thank you very much for raising this issue. The strength of Arduino lies within the minimal API which it exposes. Therefore any addition to the standard Arduino API has to be carefully considered and must be ported to all available cores, should the introduction of an additional API call be decided. As of right now differential ADCs are not a priority which is why I am closing this issue.

**Comment by Harvie** [comment]
![image](https://user-images.githubusercontent.com/276504/65071424-06d9d280-d98f-11e9-90bb-0b7ece2d58ac.png)
