### ISSUE TITLE
implement pullrequest https://github.com/arduino/Arduino/pull/7544  {build.path}/{archive_file} to {archive_file_path}

### ISSUE THREAD

**Issue by jantje** [arduino/ArduinoCore-avr#14]
I created a pull request on Arduino/arduino  to change 
recipe.c.combine.pattern=... "{build.path}/{archive_file}" ...
to
recipe.c.combine.pattern=... "{archive_file_path}" ...

in the platform.txt
given the move of repositories I closed this issue
FYI @per1234 confirms this works
https://github.com/arduino/Arduino/pull/7544

**Comment by per1234** [comment]
To be clear, I verified compilation does not fail when using the version of platform.txt proposed in https://github.com/arduino/Arduino/pull/7544 (change `{build.path}/{archive_file}` to `{archive_file_path}` with Arduino IDE 1.6.5-r5, which predates the addition of `{archive_file_path}`. This backwards compatibility was provided by https://github.com/arduino/ArduinoCore-avr/commit/33c9558641d15d63d8f7857810f70e05d4e43d5d. This is important since Boards Manager allows new versions of Arduino AVR Boards to be installed on old versions of the Arduino IDE.
