### ISSUE TITLE
Distribute pkg-config files along with the headers

### ISSUE THREAD

**Issue by doronbehar** [arduino/ArduinoCore-avr#29]
From the [pkg-config website](https://www.freedesktop.org/wiki/Software/pkg-config/):

> pkg-config is a helper tool used when compiling applications and libraries.

Besides the Arduino IDE, other build systems like GNU Makefiles, use `.pc` files (read the [man page](https://jlk.fjfi.cvut.cz/arch/manpagesman/core/pkgconf/pkgconf.1.en)) to easily know the compiler flags needed for certain headers to be used. Usually that sums up to `-I<include_dir>`s and `-l<libraries>`s.

Adding `.pc` files to the core files of AVR and other cores could prove a lot the integration of the Arduino IDE with other build systems.

**Comment by lxrobotics** [comment]
Hi @doronbehar :wave: Since we do have both [arduino-builder](https://github.com/arduino/arduino-builder) and [arduino-cli](https://github.com/arduino/arduino-cli) integration with other IDEs/build systems should be fairly easy. If you still think the addition of `.pc` files would be benefitial to a substantial amount of Arduino users please provide a PR or repoen this issue.
